### ISSUE TITLE
Typo in Int declaration

### ISSUE THREAD

**Issue by jordanmzlong** [r9y9/ConstantQ.jl#1]
There's a typo in cqt.jl, line 176, where Int is declared as int. I fixed this and now there is an error with "invalid redefinition of constant KernelMatrix". I'm new to Julia and am not sure how to fix this. Any help would be appreciated.

**Comment by r9y9** [comment]
Should be fixed by https://github.com/r9y9/ConstantQ.jl/commit/1bb3b067d9c885aba30f52062abd355d92694bc7.
